services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080-8090:8080"
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=database'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
