services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      spring.datasource.url: jdbc:postgresql://postgres:5432/database
      spring.datasource.username: admin
      spring.datasource.password: admin
    ports:
      - "8081-8090:8080"
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=database'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - 8080:8080
